#!/usr/bin/env python3
"""
hydrate_candidate_details.py
─────────────────────────────
Fetches raw decision JSON from the Diavgeia API for ADAs that are marked
"needs_hydration" in candidates.json (generated by build_intelligence_dossier.py).

This is the "narrow" half of the "search-wide, hydrate-narrow" strategy.
Only high-value ADAs are fetched — not everything.

Inputs:
  data/{org}/candidates.json        — ranked list with needs_hydration flag

Outputs:
  data/{org}/decisions/{ada}.json   — one raw JSON file per fetched ADA
  data/{org}/hydration_log.json     — success / failure log

Usage:
  python scripts/hydrate_candidate_details.py --org 6166
  python scripts/hydrate_candidate_details.py --org 6166 --limit 50
  python scripts/hydrate_candidate_details.py --org 6166 --limit 100 --delay 0.5
  python scripts/hydrate_candidate_details.py --org 6166 --dry-run
  python scripts/hydrate_candidate_details.py --org 6166 --ada-list "ADA1,ADA2,ADA3"
  python scripts/hydrate_candidate_details.py --org 6166 --force   # re-fetch all

MVP loop position:
  After:  build_intelligence_dossier.py  (which generates candidates.json)
  Before: build_intelligence_dossier.py  (re-run to incorporate new JSONs)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from datetime import datetime
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.parse import quote
from urllib.request import Request, urlopen

# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────

DIAVGEIA_API = "https://diavgeia.gov.gr/opendata"

DEFAULT_DELAY   = 0.8   # seconds between API calls (respectful default)
REQUEST_TIMEOUT = 15    # seconds per request

USER_AGENT = (
    "DiavgeiaIntelligencePipeline/1.0 "
    "(municipal transparency research; github.com/your-repo)"
)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def safe_ada_filename(ada: str) -> str:
    """Convert ADA to a filesystem-safe filename."""
    return re.sub(r'[\\/*?:"<>|]', "_", ada) + ".json"


def load_json_safe(path: Path):
    if not path.exists():
        return None
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def save_json(path: Path, data: dict):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def load_candidates(candidates_path: Path) -> list[dict]:
    data = load_json_safe(candidates_path)
    if isinstance(data, list):
        return data
    return []


def load_hydration_log(log_path: Path) -> dict:
    data = load_json_safe(log_path)
    if isinstance(data, dict):
        return data
    return {"successes": [], "failures": [], "skipped": []}


# ─────────────────────────────────────────────────────────────────────────────
# Diavgeia API call
# ─────────────────────────────────────────────────────────────────────────────

def fetch_decision(ada: str, timeout: int = REQUEST_TIMEOUT) -> tuple[dict | None, str | None]:
    """
    Fetch a single decision from the Diavgeia API.

    Returns:
      (data, None)        on success
      (None, error_msg)   on failure
    """
    # URL-encode the ADA — Greek characters must be percent-encoded for HTTP
    ada_encoded = quote(ada, safe="")
    url = f"{DIAVGEIA_API}/decisions/{ada_encoded}.json"
    req = Request(url, headers={"Accept": "application/json", "User-Agent": USER_AGENT})

    try:
        with urlopen(req, timeout=timeout) as resp:
            if resp.status == 200:
                return json.loads(resp.read().decode("utf-8")), None
            return None, f"HTTP {resp.status}"

    except HTTPError as e:
        if e.code == 404:
            return None, "not_found"
        if e.code == 429:
            return None, "rate_limited"
        return None, f"http_{e.code}"

    except URLError as e:
        return None, f"url_error:{e.reason}"

    except json.JSONDecodeError as e:
        return None, f"json_error:{e}"

    except Exception as e:  # noqa: BLE001
        return None, f"unexpected:{e}"


# ─────────────────────────────────────────────────────────────────────────────
# Main hydration loop
# ─────────────────────────────────────────────────────────────────────────────

def hydrate(
    org: str,
    data_dir: Path,
    limit: int = 100,
    delay: float = DEFAULT_DELAY,
    ada_list: list[str] | None = None,
    force: bool = False,
    dry_run: bool = False,
    min_score: int = 0,
) -> dict:

    org_dir       = data_dir / org
    decisions_dir = org_dir / "decisions"
    candidates_path = org_dir / "candidates.json"
    log_path      = org_dir / "hydration_log.json"

    decisions_dir.mkdir(parents=True, exist_ok=True)

    # ── Determine target ADA list ──────────────────────────────────────────
    if ada_list:
        # Explicit overide — fetch exactly these ADAs
        targets = [
            {"ada": a, "score": 0, "decision_type": "explicit", "subject": ""}
            for a in ada_list
        ]
        print(f"[hydrate] Explicit ADA list: {len(targets)} items")

    else:
        candidates = load_candidates(candidates_path)
        if not candidates:
            print(f"[hydrate] ERROR: candidates.json not found or empty at:\n  {candidates_path}")
            print("[hydrate] Run build_intelligence_dossier.py first to generate it.")
            sys.exit(1)

        if force:
            targets = candidates
            print(f"[hydrate] --force: targeting all {len(targets)} candidates")
        else:
            targets = [c for c in candidates if c.get("needs_hydration", False)]
            print(f"[hydrate] {len(candidates)} candidates total → {len(targets)} need hydration")

        if min_score > 0:
            before = len(targets)
            targets = [t for t in targets if t.get("score", 0) >= min_score]
            print(f"[hydrate] Score filter (≥ {min_score}): {before} → {len(targets)}")

    targets = targets[:limit]
    print(f"[hydrate] Will fetch up to {len(targets)} ADAs  (--limit {limit})")

    if not targets:
        print("[hydrate] Nothing to do — all candidates already hydrated.")
        return {"fetched": 0, "failed": 0, "skipped": 0}

    # ── Dry-run preview ───────────────────────────────────────────────────
    if dry_run:
        print("\n[hydrate] DRY RUN — no API calls made\n")
        print(f"  {'#':>4}  {'Score':>5}  {'ADA':<20}  Subject")
        print(f"  {'─'*4}  {'─'*5}  {'─'*20}  {'─'*60}")
        for i, t in enumerate(targets[:30], 1):
            print(f"  {i:>4}  {t.get('score','?'):>5}  {t['ada']:<20}  {t.get('subject','')[:60]}")
        if len(targets) > 30:
            print(f"  ... and {len(targets)-30} more")
        return {"fetched": 0, "failed": 0, "skipped": 0}

    # ── Hydration loop ────────────────────────────────────────────────────
    log = load_hydration_log(log_path)
    fetched = failed = skipped = 0
    total = len(targets)

    print(f"\n[hydrate] Starting at {datetime.now().strftime('%H:%M:%S')} · delay={delay}s/req")
    print(f"  {'#':>4}  {'Status':<8}  {'ADA':<22}  Info")
    print(f"  {'─'*4}  {'─'*8}  {'─'*22}  {'─'*50}")

    for i, target in enumerate(targets, 1):
        ada       = target["ada"]
        json_path = decisions_dir / safe_ada_filename(ada)

        # Skip if already on disk and not forced
        if json_path.exists() and not force:
            skipped += 1
            log["skipped"].append({"ada": ada, "ts": datetime.now().isoformat()})
            print(f"  {i:>4}  SKIP      {ada:<22}  already hydrated")
            continue

        # Fetch
        data, err = fetch_decision(ada)

        if data is not None:
            save_json(json_path, data)
            fetched += 1

            # Build a short info string for the log line
            subj_preview = (data.get("subject") or "")[:50]
            efv    = data.get("extraFieldValues") or {}
            aw     = efv.get("awardAmount") or {}
            amount = aw.get("amount")
            amt_s  = f" · €{amount:,.0f}" if amount is not None else ""

            print(f"  {i:>4}  OK        {ada:<22}  {subj_preview}{amt_s}")
            log["successes"].append({
                "ada": ada,
                "ts": datetime.now().isoformat(),
                "subject": (data.get("subject") or "")[:120],
                "amount": amount,
            })

        else:
            failed += 1
            print(f"  {i:>4}  FAIL      {ada:<22}  {err}")
            log["failures"].append({
                "ada": ada,
                "ts": datetime.now().isoformat(),
                "error": err,
            })

            # Back off hard on rate limiting
            if err == "rate_limited":
                backoff = 15
                print(f"  {'':>4}  {'':8}  {'Rate limit hit':22}  backing off {backoff}s ...")
                time.sleep(backoff)

        # Persist log every 10 records
        if i % 10 == 0:
            save_json(log_path, log)

        # Polite delay between calls (skip after last item)
        if i < total:
            time.sleep(delay)

    # Final log save
    save_json(log_path, log)

    print(f"\n[hydrate] Done at {datetime.now().strftime('%H:%M:%S')}")
    print(f"  Fetched : {fetched}")
    print(f"  Failed  : {failed}")
    print(f"  Skipped : {skipped}")
    print(f"  Log     : {log_path}")
    print(f"\n[hydrate] Next step — rebuild dossier to incorporate new data:")
    print(f"  python scripts/build_intelligence_dossier.py --org {org}")

    return {"fetched": fetched, "failed": failed, "skipped": skipped}


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Hydrate high-value ADA candidates from the Diavgeia API.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--org", required=True,
                        help="Organisation UID (e.g. 6166)")
    parser.add_argument("--data-dir", default="./data",
                        help="Root data directory (default: ./data)")
    parser.add_argument("--limit", type=int, default=100,
                        help="Max ADAs to fetch per run (default: 100)")
    parser.add_argument("--delay", type=float, default=DEFAULT_DELAY,
                        help=f"Seconds between API calls (default: {DEFAULT_DELAY})")
    parser.add_argument("--min-score", type=int, default=0,
                        help="Only hydrate candidates with score ≥ N (default: 0 = all)")
    parser.add_argument("--ada-list", default=None,
                        help="Comma-separated explicit ADA list (bypasses candidates.json)")
    parser.add_argument("--force", action="store_true",
                        help="Re-fetch even if the JSON already exists on disk")
    parser.add_argument("--dry-run", action="store_true",
                        help="Preview what would be fetched — no API calls made")

    args = parser.parse_args()

    ada_list = (
        [a.strip() for a in args.ada_list.split(",") if a.strip()]
        if args.ada_list else None
    )

    hydrate(
        org=args.org,
        data_dir=Path(args.data_dir),
        limit=args.limit,
        delay=args.delay,
        ada_list=ada_list,
        force=args.force,
        dry_run=args.dry_run,
        min_score=args.min_score,
    )


if __name__ == "__main__":
    main()
